name: REAACH-inscriptions
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.8.2
  - numpy=1.26.3
  - pip=23.3.1
  - python=3.12.1
  - scikit-spatial=6.8.1
  - scipy=1.11.4
  - pip:
      - pywavefront==1.3.3
